# Generated by Django 4.2.17 on 2025-04-18 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_nickname', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, help_text='Singkatan 3‑8 huruf, mis. FCB, BVB', max_length=8)),
                ('address', models.TextField()),
                ('coach_name', models.CharField(max_length=100)),
                ('coach_phone', models.CharField(max_length=15)),
                ('captain_name', models.CharField(max_length=100)),
                ('captain_phone', models.CharField(max_length=15)),
                ('supporter_name', models.CharField(max_length=100)),
                ('instagram_account', models.CharField(blank=True, max_length=100)),
                ('achievements', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('team_photo', models.ImageField(upload_to='team_photos/')),
                ('category', models.CharField(choices=[('sma', 'SMA'), ('kuliah', 'Kuliah'), ('profesional', 'Profesional')], default='sma', max_length=20)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('whitelist', 'Whitelist'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('is_main', models.BooleanField(default=False, help_text='Tick for 12 flagship clubs')),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('kiper', 'Kiper'), ('anchor', 'Anchor'), ('flank', 'Flank'), ('pivot', 'Pivot')], max_length=20)),
                ('jersey_number', models.CharField(max_length=3)),
                ('guardian_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photos/')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='supporting_documents/')),
                ('is_captain', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team')),
            ],
        ),
    ]
